---
- hosts: {hosts}
  gather_facts: no
  become: yes
  tasks:
    - name: create user group
      group:
        name: {user}
        state: present
    - name: create user
      user:
        name: {user}
        group: {user}
        shell: /bin/bash
        state: present
        generate_ssh_key: yes
        ssh_key_file: .ssh/id_rsa
        
    - name: import ssh key
      authorized_key:
        user: {user}
        state: present
        key: "{{ lookup('file', '{sshkey}') }}"
        
    - name: chmod ssh permission
      file:
        path: /home/{user}/.ssh
        state: present
        mode: '0700'
    
    - name: chmod ssh authorized_key permission
      file:
        path: /home/{user}/.ssh/authorized_key
        state: present
        mode: '0600'